name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  changeset-check:
    name: Require Changeset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: "22"

      - run: npm install

      - name: Debug actor
        run: echo "Actor is ${{ github.actor }}"

      - name: Check for changeset
        if: "github.actor != 'dependabot[bot]' && github.actor != 'app/dependabot'"
        run: npx changeset status --since=origin/main
